codecov:
  # The default branch is used to identify:
  #  Which branch to cache the repository YAML for UI changes.
  #  Which branch is the first branch on the repository dashboard in Codecov.
  branch: main
  # Show the Codecov status without waiting for other status checks to complete or pass.
  require_ci_to_pass: no

comment: false

github_checks:
  # Specify whether to use GitHub Checks annotations or normal statuses.
  annotations: true

coverage:
  status:
    project:
      default:
        # `auto` will use the coverage from the base commit (pull request base or parent commit) coverage to compare against.
        target: auto
        # Allow the coverage to drop by X% for the project, and posting a success status.
        threshold: 2%
        flags:
          - unit-tests

flag_management:
  default_rules:
    carryforward: true
