// // Copyright 2022 Antrea Authors.
// //
// // Licensed under the Apache License, Version 2.0 (the "License");
// // you may not use this file except in compliance with the License.
// // You may obtain a copy of the License at
// //
// //      http://www.apache.org/licenses/LICENSE-2.0
// //
// // Unless required by applicable law or agreed to in writing, software
// // distributed under the License is distributed on an "AS IS" BASIS,
// // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// // See the License for the specific language governing permissions and
// // limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: antrea.io/nephe/pkg/cloudprovider/securitygroup (interfaces: CloudSecurityGroupInterface)

// Package cloudsecurity is a generated GoMock package.
package cloudsecurity

import (
	reflect "reflect"

	cloudresource "antrea.io/nephe/pkg/cloudprovider/cloudresource"
	gomock "github.com/golang/mock/gomock"
)

// MockCloudSecurityGroupInterface is a mock of CloudSecurityGroupInterface interface.
type MockCloudSecurityGroupInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCloudSecurityGroupInterfaceMockRecorder
}

// MockCloudSecurityGroupInterfaceMockRecorder is the mock recorder for MockCloudSecurityGroupInterface.
type MockCloudSecurityGroupInterfaceMockRecorder struct {
	mock *MockCloudSecurityGroupInterface
}

// NewMockCloudSecurityGroupInterface creates a new mock instance.
func NewMockCloudSecurityGroupInterface(ctrl *gomock.Controller) *MockCloudSecurityGroupInterface {
	mock := &MockCloudSecurityGroupInterface{ctrl: ctrl}
	mock.recorder = &MockCloudSecurityGroupInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudSecurityGroupInterface) EXPECT() *MockCloudSecurityGroupInterfaceMockRecorder {
	return m.recorder
}

// CloudProviderSupportsRuleAction mocks base method.
func (m *MockCloudSecurityGroupInterface) CloudProviderSupportsRuleAction(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudProviderSupportsRuleAction", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CloudProviderSupportsRuleAction indicates an expected call of CloudProviderSupportsRuleAction.
func (mr *MockCloudSecurityGroupInterfaceMockRecorder) CloudProviderSupportsRuleAction(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudProviderSupportsRuleAction", reflect.TypeOf((*MockCloudSecurityGroupInterface)(nil).CloudProviderSupportsRuleAction), arg0)
}

// CloudProviderSupportsRuleName mocks base method.
func (m *MockCloudSecurityGroupInterface) CloudProviderSupportsRuleName(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudProviderSupportsRuleName", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CloudProviderSupportsRuleName indicates an expected call of CloudProviderSupportsRuleName.
func (mr *MockCloudSecurityGroupInterfaceMockRecorder) CloudProviderSupportsRuleName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudProviderSupportsRuleName", reflect.TypeOf((*MockCloudSecurityGroupInterface)(nil).CloudProviderSupportsRuleName), arg0)
}

// CloudProviderSupportsRulePriority mocks base method.
func (m *MockCloudSecurityGroupInterface) CloudProviderSupportsRulePriority(arg0 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloudProviderSupportsRulePriority", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CloudProviderSupportsRulePriority indicates an expected call of CloudProviderSupportsRulePriority.
func (mr *MockCloudSecurityGroupInterfaceMockRecorder) CloudProviderSupportsRulePriority(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloudProviderSupportsRulePriority", reflect.TypeOf((*MockCloudSecurityGroupInterface)(nil).CloudProviderSupportsRulePriority), arg0)
}

// CreateSecurityGroup mocks base method.
func (m *MockCloudSecurityGroupInterface) CreateSecurityGroup(arg0 *cloudresource.CloudResource, arg1 bool) <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityGroup", arg0, arg1)
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// CreateSecurityGroup indicates an expected call of CreateSecurityGroup.
func (mr *MockCloudSecurityGroupInterfaceMockRecorder) CreateSecurityGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityGroup", reflect.TypeOf((*MockCloudSecurityGroupInterface)(nil).CreateSecurityGroup), arg0, arg1)
}

// DeleteSecurityGroup mocks base method.
func (m *MockCloudSecurityGroupInterface) DeleteSecurityGroup(arg0 *cloudresource.CloudResource, arg1 bool) <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecurityGroup", arg0, arg1)
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// DeleteSecurityGroup indicates an expected call of DeleteSecurityGroup.
func (mr *MockCloudSecurityGroupInterfaceMockRecorder) DeleteSecurityGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecurityGroup", reflect.TypeOf((*MockCloudSecurityGroupInterface)(nil).DeleteSecurityGroup), arg0, arg1)
}

// GetSecurityGroupSyncChan mocks base method.
func (m *MockCloudSecurityGroupInterface) GetSecurityGroupSyncChan() <-chan cloudresource.SynchronizationContent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroupSyncChan")
	ret0, _ := ret[0].(<-chan cloudresource.SynchronizationContent)
	return ret0
}

// GetSecurityGroupSyncChan indicates an expected call of GetSecurityGroupSyncChan.
func (mr *MockCloudSecurityGroupInterfaceMockRecorder) GetSecurityGroupSyncChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroupSyncChan", reflect.TypeOf((*MockCloudSecurityGroupInterface)(nil).GetSecurityGroupSyncChan))
}

// UpdateSecurityGroupMembers mocks base method.
func (m *MockCloudSecurityGroupInterface) UpdateSecurityGroupMembers(arg0 *cloudresource.CloudResource, arg1 []*cloudresource.CloudResource, arg2 bool) <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecurityGroupMembers", arg0, arg1, arg2)
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// UpdateSecurityGroupMembers indicates an expected call of UpdateSecurityGroupMembers.
func (mr *MockCloudSecurityGroupInterfaceMockRecorder) UpdateSecurityGroupMembers(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecurityGroupMembers", reflect.TypeOf((*MockCloudSecurityGroupInterface)(nil).UpdateSecurityGroupMembers), arg0, arg1, arg2)
}

// UpdateSecurityGroupRules mocks base method.
func (m *MockCloudSecurityGroupInterface) UpdateSecurityGroupRules(arg0 *cloudresource.CloudResource, arg1, arg2 []*cloudresource.CloudRule) <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecurityGroupRules", arg0, arg1, arg2)
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// UpdateSecurityGroupRules indicates an expected call of UpdateSecurityGroupRules.
func (mr *MockCloudSecurityGroupInterfaceMockRecorder) UpdateSecurityGroupRules(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecurityGroupRules", reflect.TypeOf((*MockCloudSecurityGroupInterface)(nil).UpdateSecurityGroupRules), arg0, arg1, arg2)
}
