# permissions for end users to edit cloudprovideraccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudprovideraccount-editor-role
rules:
- apiGroups:
  - crd.cloud.antrea.io
  resources:
  - cloudprovideraccounts
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - crd.cloud.antrea.io
  resources:
  - cloudprovideraccounts/status
  verbs:
  - get
