# permissions for end users to edit externalentities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalentity-editor-role
rules:
- apiGroups:
  - crd.antrea.io
  resources:
  - externalentities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - externalentities/status
  verbs:
  - get
