name: Process new release

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - uses: actions/checkout@v3
    - name: Build assets
      env:
        TAG: ${{ github.ref }}
        PRERELEASE: ${{ github.event.release.prerelease }}
      run: |
        mkdir assets
        VERSION="${TAG:10}" ./hack/release/prepare-assets.sh ./assets
    - name: Upload nephe.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/nephe.yml
        asset_name: nephe.yml
        asset_content_type: application/octet-stream
    - name: Upload install-vm-agent-wrapper.sh
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/install-vm-agent-wrapper.sh
        asset_name: install-vm-agent-wrapper.sh
        asset_content_type: application/octet-stream
    - name: Upload install-vm-agent-wrapper.ps1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/install-vm-agent-wrapper.ps1
        asset_name: install-vm-agent-wrapper.ps1
        asset_content_type: application/octet-stream
